# Linear Regression model example

In [1]:
# To perform any machine learning model it is necessary to have a data set in this example we are going to 
import pandas as pd

In [2]:
data_set=pd.read_csv('Salary_Data.csv')

In [4]:
data_set

YearsExperience    Salary
0               1.1   39343.0
1               1.3   46205.0
2               1.5   37731.0
3               2.0   43525.0
4               2.2   39891.0
5               2.9   56642.0
6               3.0   60150.0
7               3.2   54445.0
8               3.2   64445.0
9               3.7   57189.0
10              3.9   63218.0
11              4.0   55794.0
12              4.0   56957.0
13              4.1   57081.0
14              4.5   61111.0
15              4.9   67938.0
16              5.1   66029.0
17              5.3   83088.0
18              5.9   81363.0
19              6.0   93940.0
20              6.8   91738.0
21              7.1   98273.0
22              7.9  101302.0
23              8.2  113812.0
24              8.7  109431.0
25              9.0  105582.0
26              9.5  116969.0
27              9.6  112635.0
28             10.3  122391.0
29             10.5  121872.0

In [3]:
from sklearn.linear_model import LinearRegression

In [4]:
model=LinearRegression()

In [5]:
data_set.columns

Index(['YearsExperience', 'Salary'], dtype='object')

In [6]:
x=data_set['YearsExperience'].values.reshape(30,1)
y=data_set['Salary']

In [7]:
import numpy

array([[ 1.1],
       [ 1.3],
       [ 1.5],
       [ 2. ],
       [ 2.2],
       [ 2.9],
       [ 3. ],
       [ 3.2],
       [ 3.2],
       [ 3.7],
       [ 3.9],
       [ 4. ],
       [ 4. ],
       [ 4.1],
       [ 4.5],
       [ 4.9],
       [ 5.1],
       [ 5.3],
       [ 5.9],
       [ 6. ],
       [ 6.8],
       [ 7.1],
       [ 7.9],
       [ 8.2],
       [ 8.7],
       [ 9. ],
       [ 9.5],
       [ 9.6],
       [10.3],
       [10.5]])

In [8]:
x.shape

(30, 1)

In [9]:
model.fit(x,y)

LinearRegression()

In [10]:
model.coef_

array([9449.96232146])

In [11]:
model.intercept_

25792.20019866871

In [12]:
model.predict([[2.5]])

array([49417.10600231])

In [13]:
import joblib

In [14]:
joblib.dump(model ,"myModel.pkl")

['myModel.pkl']